# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter Feed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter Feed

  target 'Twitter FeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
